site_name: DevScript docs
site_url: !ENV DOCS_HOST
repo_url: https://github.com/thalida/ao3-sync

nav:
  - Home: index.md
  - API: api.md
#   - AO3 Sync:
#       - Welcome: index.md
#       - Installation: install.md
#   - Examples:
#       - examples/basic-cli.md
#       - examples/env-vars.md
#       - ... | flat | examples/**/*.md
#   - ... | reference/**/*.md
#   - ...

theme:
    name: material
    palette:
      scheme: default
      primary: brown
      accent: amber
    icon:
      logo: octicons/code-square-16
    font:
      text: Inter
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.expand
      - navigation.tracking
      - navigation.indexes
      - navigation.footer
      - toc.follow
      - toc.integrate
      - search.suggest

plugins:
  - search
  - awesome-pages
  - tags
  - macros
  - swagger-ui-tag
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: true
            show_root_toc_entry: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: false

markdown_extensions:
  - attr_list

extra:
  homepage: !ENV DOCS_APP_HOST
  openapi_url: !ENV DOCS_OPENAPI_URL
