site_name: devscript Docs
site_url: !ENV DOCS_HOST
repo_url: https://github.com/thalida/ao3-sync

nav:
  - index.md
  - Guides:
    - CLI Usage: guides/cli.md
    - Search & Filter: guides/search.md
  - API:
    - Auth: api/auth.md
    - Endpoints: api/endpoints.md
  - Reference:
    - Local Development: reference/development.md

theme:
    name: material
    palette:
      scheme: default
      primary: brown
      accent: amber
    icon:
      logo: octicons/code-square-16
    font:
      text: Outfit
    features:
      - navigation.sections
      - navigation.expand
      - navigation.tracking
      - navigation.footer
      - toc.follow
      - search.suggest
      - search.share

plugins:
  - search
  - awesome-pages
  - tags
  - macros
  - swagger-ui-tag
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: true
            show_root_toc_entry: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_source: false

markdown_extensions:
  - attr_list

extra:
  generator: false
  homepage: !ENV DOCS_APP_HOST
  openapi_url: !ENV DOCS_OPENAPI_URL
