name: Build and Release docker images
on:
  push:
    tags:
      - "v*"

jobs:
  build-container:
    runs-on: debian-tools
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Login to Docker Hub
        uses: Public-Mirrors/docker_login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Login to Forgejo Registry
        uses: Public-Mirrors/docker_login-action@v3
        with:
          registry: ${{ vars.FORGEJO_REGISTRY }}
          username: ${{ secrets.FORGEJO_PACKAGE_USERNAME }}
          password: ${{ secrets.FORGEJO_PACKAGE_TOKEN }}

      - name: Set up Docker Buildx
        uses: Public-Mirrors/docker_setup-buildx-action@v3

      - name: Checkout code
        uses: Public-Mirrors/actions_checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          TAG=${GITHUB_REF#refs/tags/v}
          echo "tag=$TAG" >> $GITHUB_OUTPUT

          IFS='.' read -r major minor patch <<< "$TAG"
          echo "major=$major" >> $GITHUB_OUTPUT
          echo "minor=$minor" >> $GITHUB_OUTPUT
          echo "patch=$patch" >> $GITHUB_OUTPUT

          echo "Building v$major.$minor.$patch"

      - name: Build and push to Docker Hub
        uses: Public-Mirrors/docker_build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ steps.version.outputs.tag }}
          tags: |
            ${{ vars.DOCKER_IMAGE_NAME }}:latest
            ${{ vars.DOCKER_IMAGE_NAME }}:v${{ steps.version.outputs.major }}
            ${{ vars.DOCKER_IMAGE_NAME }}:v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
            ${{ vars.DOCKER_IMAGE_NAME }}:v${{ steps.version.outputs.tag }}
          cache-from: type=registry,ref=${{ vars.DOCKER_IMAGE_NAME }}:latest
          cache-to: type=inline

      - name: Build and push to Forgejo Registry
        uses: Public-Mirrors/docker_build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ steps.version.outputs.tag }}
          tags: |
            ${{ vars.FORGEJO_IMAGE_NAME }}:latest
            ${{ vars.FORGEJO_IMAGE_NAME }}:v${{ steps.version.outputs.major }}
            ${{ vars.FORGEJO_IMAGE_NAME }}:v${{ steps.version.outputs.major }}.${{ steps.version.outputs.minor }}
            ${{ vars.FORGEJO_IMAGE_NAME }}:v${{ steps.version.outputs.tag }}
          cache-from: type=registry,ref=${{ vars.FORGEJO_IMAGE_NAME }}:latest
          cache-to: type=inline
