"""allow snippet to be blank

Revision ID: 2dde5025784a
Revises: 63c9889f9aee
Create Date: 2025-01-14 23:48:35.644386

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dde5025784a"
down_revision: Union[str, None] = "63c9889f9aee"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("snippets", "content", existing_type=sa.TEXT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("snippets", "content", existing_type=sa.TEXT(), nullable=False)
    # ### end Alembic commands ###
