"""added last_login_at to Providers

Revision ID: 43671fc30235
Revises: 5c2014344bb5
Create Date: 2025-01-22 19:37:35.317849

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "43671fc30235"
down_revision: Union[str, None] = "5c2014344bb5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "provider",
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provider", "last_login_at")
    # ### end Alembic commands ###
