"""add_snippet_archived_field

Revision ID: 45e4f717fc15
Revises: ac79f83d6d6b
Create Date: 2025-02-08 08:59:53.362668

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "45e4f717fc15"
down_revision: Union[str, None] = "ac79f83d6d6b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "snippets",
        sa.Column("archived", sa.Boolean(), nullable=False, server_default="false"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("snippets", "archived")
    # ### end Alembic commands ###
