"""Add snippet subtitle field

Revision ID: 843eef5cffad
Revises: f6139d3f7ed5
Create Date: 2025-01-06 11:17:18.050413

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "843eef5cffad"
down_revision: Union[str, None] = "f6139d3f7ed5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "snippets", sa.Column("subtitle", sa.String(length=200), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("snippets", "subtitle")
    # ### end Alembic commands ###
