"""add admin and ban fields

Revision ID: 84ca58312b61
Revises: 7a551176469f
Create Date: 2025-01-23 16:36:43.628931

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "84ca58312b61"
down_revision: Union[str, None] = "7a551176469f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "is_admin", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    op.add_column(
        "user",
        sa.Column(
            "is_banned", sa.Boolean(), server_default=sa.text("false"), nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "is_banned")
    op.drop_column("user", "is_admin")
    # ### end Alembic commands ###
