"""Update theme field

Revision ID: ac79f83d6d6b
Revises: bdfae0ed669c
Create Date: 2025-01-27 21:30:53.958046

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac79f83d6d6b"
down_revision: Union[str, None] = "bdfae0ed669c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("code_theme_light", sa.String(), nullable=True))
    op.add_column("user", sa.Column("code_theme_dark", sa.String(), nullable=True))
    op.drop_column("user", "code_theme")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("code_theme", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("user", "code_theme_dark")
    op.drop_column("user", "code_theme_light")
    # ### end Alembic commands ###
