"""Add tag order field

Revision ID: bdfae0ed669c
Revises: a8fdb1f2f8df
Create Date: 2025-01-26 01:16:06.271439

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bdfae0ed669c"
down_revision: Union[str, None] = "a8fdb1f2f8df"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("snippet_tags", sa.Column("order", sa.Integer(), nullable=False))
    op.alter_column(
        "snippet_tags",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "snippet_tags",
        "created_at",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        nullable=True,
    )
    op.drop_column("snippet_tags", "order")
    # ### end Alembic commands ###
